### ISSUE TITLE
Callable type hint does not work for callable classes

### ISSUE THREAD

**Issue by FeryET** [omni-us/jsonargparse#110]
Hi.

I'm trying to typehint my project accordingly, and I have something like this:
```
# module.py
class A:
    def __call__(self):
         pass

class B:
   def __init__(self, arr: Sequence[Callable]):
        self.arr = arr 
```
I have this config file:
```
# config.yaml
item_b:
     arr: 
       - class_path: module.A
       - class_path: module.A
       - class_path: module.A
```

But this will lead to some incomprehensible errors that will finally show that 
```
Configuration check failed :: Parser key "item_b.arr": Not of type typing.Callable. Expected a dot import path string
```

This is actually a reproduction of a code I'm trying to implement using PytorchLightning's new CLI, but I think the issue comes from jsonargparse.
