### ISSUE TITLE
Fucntion as an argument 

### ISSUE THREAD

**Issue by kenenbek** [omni-us/jsonargparse#149]
If I want to use CLI to initialize some `Data` object I should use:

`python train.py  --config data.yaml`

```
data:
  class_path: foo.datasets.Data
  init_args:
    data_dir: data
```

But what if one the `init_arguments` is a function? How can I pass a reference to it like this? 

```
data:
  class_path: foo.datasets.my_data
  init_args:
    data_dir: data
    filter: foo.datasets.filter1
```

`foo.datasets.filter1` is a function.

Thank you for attention.
