### ISSUE TITLE
Defining class_path before init_args does not work, but switching the order does work.

### ISSUE THREAD

**Issue by basveeling** [omni-us/jsonargparse#161]
## 🐛 Bug report

Using LightningCLI, when setting the `model` property in a yaml file, the order of class_path and init_args matters. class_path before init_args causes a ParsingError.

### To reproduce

Setup a LightingCLI with a base class BaseModelClass(LightningModule)
`train.py` would be something along the lines of
```
LightningCLI(model_class=BaseModelClass, ...)
```

Config file `a.yaml`:
```
model:
   class_path: SubclassedModelClass
   init_args:
     a: b
```

Config file `b.yaml`
```
model:
   init_args:
     a: b
   class_path: SubclassedModelClass
```
Run it as follows
`python train.py fit -c a.yaml`

```
jsonargparse.util.ParserError: Configuration check failed :: Parser key "model": Type <class 'BaseModelClass'> expects: a class path (str); or a dict with a class_path entry; or a dict with init_args (if class path given previously). Got "Namespace(init_args=Namespace(a="b"))".
```
(Notice the missing **class_path**)

Then run with the alternative order
`python train.py fit -c b.yaml`
Which runs successfully.

### Expected behavior

Both orders should work

### Environment

- jsonargparse version 4.14.0
- pytorch_lightning 1.7.4
- python 3.8.14
- `pip install jsonargparse[signatures]`
- Ubuntu
