### ISSUE TITLE
[Need help] How to init an object of a class with position parameters in yaml config file? Also how to call a func to init an object in yaml file?

### ISSUE THREAD

**Issue by shenmishajing** [omni-us/jsonargparse#407]
## 🚀 Feature request

We can init an object with keyword parameters already, which is very helpful. An example:

```yaml
  encoders:
      class_path: torch.nn.ModuleDict
      init_args:
          modules:
              table:
                class_path: torch.nn.TransformerEncoder
                init_args:
                    encoder_layer:
                        class_path: torch.nn.TransformerEncoderLayer
                        init_args:
                            d_model: 128
                            nhead: 128
                            activation: relu
                            batch_first: true
                    num_layers: 2
```

But, what should I do if I want to use a torch.nn.Sequential or other class requiring position parameters instead of ModuleDict? The init func of nn.Sequential:
```python

    @overload
    def __init__(self, *args: Module) -> None:
        ...

    @overload
    def __init__(self, arg: 'OrderedDict[str, Module]') -> None:
        ...

    def __init__(self, *args):
        super(Sequential, self).__init__()
        if len(args) == 1 and isinstance(args[0], OrderedDict):
            for key, module in args[0].items():
                self.add_module(key, module)
        else:
            for idx, module in enumerate(args):
                self.add_module(str(idx), module)
```

And, how to use a func to init an object? For example, I have a func like this:
```python
# encoder.py
def init_encoder(dim):
  return nn.Sequential(nn.Linear(dim, dim), nn.Relu())
```
What should I do if I want something like:
```yaml
  encoders:
      class_path: torch.nn.ModuleDict
      init_args:
          modules:
              table:
                method_path: encoder.init_encoder
                init_args:
                    dim: 128
```
