### ISSUE TITLE
Overwrite subconfig arguments

### ISSUE THREAD

**Issue by rusmux** [omni-us/jsonargparse#418]
## 🚀 Feature request

Allow to overwrite subconfig arguments. For example:

`evaluate.yaml`:
```yaml
model: model.yaml
data: path/to/data
```

`model.yaml`:
```yaml
class_path: path.to.Model
init_args:
  a: 1
  b: 2
  c: 3
  d: 4
  e: 5
```

I want to create `evaluate_2.yaml` with `e` argument of the model equal to something else. It would be nice to do this like this:

```yaml
model: model.yaml
  init_args:
    e: 6
```

I can do this from the CLI by passing an argument, but I would also like to do it using config.

Probably something similar has already been suggested, but I got lost in numerous problems here and in Lightning, so I would appreciate it if you could help me. Thanks!

### Motivation

To avoid duplicating configs.
