### ISSUE TITLE
[Feature request] Add arguments description as comments in print_config output

### ISSUE THREAD

**Issue by Mick605** [omni-us/jsonargparse#52]
Hello and thank you for the great library !

### Feature request
The `--print_config` feature is useful but limited: this would be great if there was a way to print a config file in YAML format containing comments to describe the arguments. I'm aware that this kind of feature depends on the format used for the dump, because JSON does not support comments.

Suggestions are:
- add an optional argument to the `ArgumentParser.dump` method to allow printing comments (only for YAML files). This will need a modification of the way the YAML is dumped
- or add list of actions and groups to public API to allow custom implementation of this feature (as is, if I'm correct, there is no way to access Action objects except `parser._actions` which is not public)

### Example script

```python
import jsonargparse

parser = jsonargparse.ArgumentParser(parse_as_dict=True, description="Test print-config")

parser.add_argument("--argument1", default=1, help="Description argument 1")
parser.add_argument("--argument2", default='VAL2', help="Description argument 2")

group = parser.add_argument_group(title='Group title')
group.add_argument("--level.argument3", default=3, help="Description argument 3")
group.add_argument("--level.argument4", default=4, required=True, help="Description argument 4")

parser.parse_args()
```

### Current behaviour

Using the --print_config option produce this output:
```
argument1: 1   
argument2: VAL2
level:
  argument3: 3 
  argument4: 4
```

### Wanted behaviour

This would be great if I could produce this kind of output (using `--print-config` or `ArgumentParser.dump` method):

```
# optional arguments:
# ----------------------

# Description argument 1 (default: 1)
argument1: 1

# Description argument 2 (default: VAL2)
argument2: VAL2

# Group title
# ------------

level:
  # Description argument 3 (default: 3)
  argument3: 3 

  # Description argument 4 (required, default: 4)
  argument4: 4
```
The file here should still be a valid YAML file. Comments used here could be the same as for the `--help` method (with types, default values, ...).
