### ISSUE TITLE
Support YAML anchors in configs for `CLI`

### ISSUE THREAD

**Issue by rusmux** [omni-us/jsonargparse#536]
## 🚀 Feature request

Support YAML anchors in configs for `CLI`.

### Motivation

Anchors reduce duplication of configuration values. For example (not necessarily like this):

```YAML
x-common-args: &common_args
  a: 1
  b: 2
  c: 3

instances:
  - class_path: __main__.MyClass
    init_args:
      name: instance_1
      <<: *common_arg
  - class_path: __main__.MyClass
    init_args:
      name: instance_2
      <<: *common_arg
  ...
```

### Pitch

YAML anchors are supported by `CLI`.

**Comment by mauvilsa** [comment]
Than you for proposing! Note that yaml anchors are supported. What isn't possible is to add keys with arbitrary names, like 'x-common-args`, which are not part of the signature. For example the following should work fine:

```yaml
instances:
  - class_path: __main__.MyClass
    init_args: &init_args
      name: instance_1
      a: 1
      b: 2
      c: 3
  - class_path: __main__.MyClass
    init_args:
      <<: *init_args
      name: instance_2
```
