### ISSUE TITLE
Any ways to support torch functions

### ISSUE THREAD

**Issue by ioangatop** [omni-us/jsonargparse#546]
## 🚀 Feature request

Hi! I would like to use torch functions straight from the `yaml` file, for example:
```yaml
class_path: SomeClass
init_args:
  process:
    class_path: torch.argmax
    init_args:
      dim: 1
```

However, I have had time to succeed, as the typing check fails, as for example the following:

```py3
class SomeClass:
  def __init__(self, process: Callable[..., torch.Tensor]) -> None:
    ...
```

The way around is to wrap them around callable classes, but it would be great to support them, like the dot imports for the torch optimizes, so I dont have to duplicate them or clear a wrapper class
