### ISSUE TITLE
Subclass arguments not saved properly with ArgumentParser.save(multifile=True) 

### ISSUE THREAD

**Issue by Andry-Bal** [omni-us/jsonargparse#63]
### Setup to reproduce the issue:

_**classes.py**_:
```
class BaseForA:
    def __init__(self, base_a_param: int):
        ...


class A(BaseForA):
    def __init__(self, base_a_param: int, a_param: int):
        super().__init__(base_a_param)


class B:
    def __init__(self, b_param: int):
        ...
```

_**test.py**_:
```
from pathlib import Path
from jsonargparse import ArgumentParser
from parser_test.classes import BaseForA, B

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_subclass_arguments(BaseForA, nested_key='a')
    parser.add_class_arguments(B, nested_key='b')
    cfg = parser.parse_args()
    Path('./saved').mkdir(exist_ok=True)
    parser.save(cfg, './saved/config.yaml', overwrite=True, multifile=True)
```

_**a_config.yaml**_:
```
class_path: parser_test.classes.A
init_args:
  base_a_param: 1
  a_param: 2
```

_**b_config.yaml**_:
```
b_param: 3
```
Run command:
`python ./test.py --a ./a_config.yaml --b ./b_config.yaml`

### Expected behavior: 
1. Dir _**saved**_ contains _**a_config.yaml**_ , _**b_config.yaml**_ and main config _**config.yaml**_
2. _**config.yaml**_:
```
a: a_config.yaml
b: b_config.yaml
```

### Current behavior:
1. Dir _**saved**_ contains _**b_config.yaml**_ and main config _**config.yaml**_ (_**a_config.yaml**_ is missing)
2. _**config.yaml**_:
```
a:
  class_path: parser_test.classes.A
  init_args:
    base_a_param: 1
    a_param: 2
b: b_config.yaml

```
