### ISSUE TITLE
CLI fails with default=None for non-Any typed arguments

### ISSUE THREAD

**Issue by adrianomartinelli** [omni-us/jsonargparse#696]
## 🐛 Bug report

Hei thanks for this nice tool!
I started to use it for various ML projects and observed the following (not sure if this is a bug though)

If I annotate my function with classes that have default arguments set to None I get errors. 
If I annotate them with any and use the `class_path` pattern it works.

### To reproduce

```yaml
# config.yaml

# config for typing RandomForestClassifier
model:
  n_estimators: 23  # works
  criterion: 'entropy'  # works
  min_samples_split: 4  # works
  max_leaf_nodes: 3  # fails

# config for typing: Any
model:
  class_path: sklearn.ensemble.RandomForestClassifier
  init_args:
    n_estimators: 23  # works
    criterion: 'entropy'  # works
    min_samples_split: 4  # works
    max_leaf_nodes: 3  # works

```

```python
# main.py

# works
from typing import Any
def main(model: Any):
    print(model)

# fails
from sklearn.ensemble import RandomForestClassifier
def main(model: RandomForestClassifier):
    print(model)


if __name__ == "__main__":
    from jsonargparse import auto_cli
    auto_cli(main, as_positional=False)
```

1. Using the CLI function

```
python main.py --config config.yaml
```

Errors with:
```
usage: none-default-fail.py [-h] [--config CONFIG] [--print_config[=flags]] [--model.help [CLASS_PATH_OR_NAME]] --model MODEL
error: Parser key "model":
  Problem with given class_path 'sklearn.ensemble.RandomForestClassifier':
    Validation failed: Key 'max_leaf_nodes' is not expected
```

With typing Any model is created as expected
```
RandomForestClassifier(criterion='entropy', max_leaf_nodes=3,
                       min_samples_split=4, n_estimators=23)

```

### Expected behavior

Both ways should work from my understanding.

### Environment

- jsonargparse version: jsonargparse==4.38.0
- Python version:  Python 3.12.1
- How jsonargparse was installed: pip
- OS:  macOS Sequoia 15.3.2
