### ISSUE TITLE
Having trouble to parse an argument of Class type

### ISSUE THREAD

**Issue by alealv** [omni-us/jsonargparse#95]
I'm using [PyTorch Lightning CLI](https://pytorch-lightning.readthedocs.io/en/1.4.9/common/lightning_cli.html) utility and I'm having an issue with two classes that need an instance of [MelSpectrogram](https://pytorch.org/audio/stable/transforms.html#melspectrogram).

I would expect them to behave like `Path` parameter, but it's not the case. The program is failing when trying to run `deserialize` so I believed I should create an appropriate function for this but I don't understand how and what is required.

### Current Code 

```python

from jsonargparse.typing import register_type

register_type(Path, type_check=lambda v, t: isinstance(v, t))
register_type(MelSpectrogram, type_check=lambda v, t: isinstance(v, t))

@dataclass
class PrxMelDataModule(pl.LightningDataModule):
    data_dir: Path
    mel_spec: MelSpectrogram
.....


class HifiGAN(LightningModule):
    def __init__(
        self,
        mel_spec: MelSpectrogram,
....


if __name__ == "__main__":
    cli = AcousticModelCLI(
        model_class=HifiGAN,
        datamodule_class=PrxMelDataModule,
    )
```

### Config
```yaml
....
model:
  mel_spec:
    center: false
    hop_length: 256
    mel_fmin: 0.0
    mel_fmax: 8000.0
    mel_fmax_loss: null
    n_fft: 1024
    normalized: false
    num_mels: 80
    sampling_rate: 22050
    win_length: 1024
    # hann_windows: {}
    # mel_bases: {}
....
data:
  data_dir: data/all
  mel_spec:
    center: false
    hop_length: 256
    mel_fmin: 0.0
    mel_fmax: 8000.0
    mel_fmax_loss: null
    n_fft: 1024
    normalized: false
    num_mels: 80
    sampling_rate: 22050
    win_length: 1024
...
```

### Help output 

```bash
usage: acoustic-model-trainer [-h] [--config CONFIG] [--print_config [={comments,skip_null}+]] [--seed_everything 
.....

<class 'hifi_gan.HifiGAN'>:
  --model.mel_spec.help CLASS
                        Show the help for the given subclass of MelSpectrogram and exit.
  --model.mel_spec MEL_SPEC
                        (required, type: <class 'MelSpectrogram'>) 
....

PrX data directory or list of dataset subdirectories:
  --data.data_dir.help CLASS
                        Show the help for the given subclass of Path and exit.
  --data.data_dir DATA_DIR
                        (required, type: <class 'Path'>)
  --data.mel_spec.help CLASS
                        Show the help for the given subclass of MelSpectrogram and exit.
  --data.mel_spec MEL_SPEC
                        (required, type: <class 'MelSpectrogram'>)
....
```

### Error
```bash
2021-10-07 19:10:21,353 - Parser - DEBUG - Skipping parameter "params" from "AdamW" because of: Parameter requested to be skipped.
2021-10-07 19:10:21,354 - Parser - DEBUG - Skipping parameter "params" from "AdamW" because of: Parameter requested to be skipped.
2021-10-07 19:10:21,354 - Parser - DEBUG - Skipping parameter "optimizer" from "ExponentialLR" because of: Parameter requested to be skipped.
2021-10-07 19:10:21,355 - Parser - DEBUG - Skipping parameter "optimizer" from "ExponentialLR" because of: Parameter requested to be skipped.
2021-10-07 19:10:21,443 - Parser - ERROR - Parser key "model.mel_spec": Not of type MelSpectrogram. unsupported operand type(s) for //: 'dict' and 'int'
usage: acoustic-model-trainer [-h] [--config CONFIG] [--print_config [={comments,skip_null}+]] [--seed_everything SEED_EVERYTHING] [--trainer.logger LOGGER] [--trainer.checkpoint_callback {true,false}] [--trainer.callbacks CALLBACKS] [--trainer.default_root_dir DEFAULT_ROOT_DIR]
                              [--trainer.gradient_clip_val GRADIENT_CLIP_VAL] [--trainer.gradient_clip_algorithm GRADIENT_CLIP_ALGORITHM] [--trainer.process_position PROCESS_POSITION] [--trainer.num_nodes NUM_NODES] [--trainer.num_processes NUM_PROCESSES]
                              [--trainer.devices DEVICES] [--trainer.gpus GPUS] [--trainer.auto_select_gpus {true,false}] [--trainer.tpu_cores TPU_CORES] [--trainer.ipus IPUS] [--trainer.log_gpu_memory LOG_GPU_MEMORY] [--trainer.progress_bar_refresh_rate PROGRESS_BAR_REFRESH_RATE]
                              [--trainer.overfit_batches OVERFIT_BATCHES] [--trainer.track_grad_norm TRACK_GRAD_NORM] [--trainer.check_val_every_n_epoch CHECK_VAL_EVERY_N_EPOCH] [--trainer.fast_dev_run FAST_DEV_RUN] [--trainer.accumulate_grad_batches ACCUMULATE_GRAD_BATCHES]
                              [--trainer.max_epochs MAX_EPOCHS] [--trainer.min_epochs MIN_EPOCHS] [--trainer.max_steps MAX_STEPS] [--trainer.min_steps MIN_STEPS] [--trainer.max_time MAX_TIME] [--trainer.limit_train_batches LIMIT_TRAIN_BATCHES]
                              [--trainer.limit_val_batches LIMIT_VAL_BATCHES] [--trainer.limit_test_batches LIMIT_TEST_BATCHES] [--trainer.limit_predict_batches LIMIT_PREDICT_BATCHES] [--trainer.val_check_interval VAL_CHECK_INTERVAL]
                              [--trainer.flush_logs_every_n_steps FLUSH_LOGS_EVERY_N_STEPS] [--trainer.log_every_n_steps LOG_EVERY_N_STEPS] [--trainer.accelerator ACCELERATOR] [--trainer.sync_batchnorm {true,false}] [--trainer.precision PRECISION]
                              [--trainer.weights_summary WEIGHTS_SUMMARY] [--trainer.weights_save_path WEIGHTS_SAVE_PATH] [--trainer.num_sanity_val_steps NUM_SANITY_VAL_STEPS] [--trainer.truncated_bptt_steps TRUNCATED_BPTT_STEPS]
                              [--trainer.resume_from_checkpoint RESUME_FROM_CHECKPOINT] [--trainer.profiler PROFILER] [--trainer.benchmark {true,false}] [--trainer.deterministic {true,false}] [--trainer.reload_dataloaders_every_n_epochs RELOAD_DATALOADERS_EVERY_N_EPOCHS]
                              [--trainer.reload_dataloaders_every_epoch {true,false}] [--trainer.auto_lr_find AUTO_LR_FIND] [--trainer.replace_sampler_ddp {true,false}] [--trainer.terminate_on_nan {true,false}] [--trainer.auto_scale_batch_size AUTO_SCALE_BATCH_SIZE]
                              [--trainer.prepare_data_per_node {true,false}] [--trainer.plugins PLUGINS] [--trainer.amp_backend AMP_BACKEND] [--trainer.amp_level AMP_LEVEL] [--trainer.distributed_backend DISTRIBUTED_BACKEND] [--trainer.move_metrics_to_cpu {true,false}]
                              [--trainer.multiple_trainloader_mode MULTIPLE_TRAINLOADER_MODE] [--trainer.stochastic_weight_avg {true,false}] [--model.mel_spec.help CLASS] [--model.mel_spec MEL_SPEC] [--model.clip_grad_val CLIP_GRAD_VAL] [--model.upsample_rates UPSAMPLE_RATES]
                              [--model.upsample_kernel_sizes UPSAMPLE_KERNEL_SIZES] [--model.upsample_initial_channel UPSAMPLE_INITIAL_CHANNEL] [--model.resblock RESBLOCK] [--model.resblock_kernel_sizes RESBLOCK_KERNEL_SIZES]
                              [--model.resblock_dilation_sizes RESBLOCK_DILATION_SIZES] [--data.data_dir.help CLASS] [--data.data_dir DATA_DIR] [--data.batch_size BATCH_SIZE] [--data.mel_spec.help CLASS] [--data.mel_spec MEL_SPEC] [--data.max_num_frames MAX_NUM_FRAMES]
                              [--data.num_workers NUM_WORKERS] [--data.splits SPLITS] [--debug] [--optimizer.discriminator.lr LR] [--optimizer.discriminator.betas BETAS] [--optimizer.discriminator.eps EPS] [--optimizer.discriminator.weight_decay WEIGHT_DECAY]
                              [--optimizer.discriminator.amsgrad AMSGRAD] [--optimizer.genertor.lr LR] [--optimizer.genertor.betas BETAS] [--optimizer.genertor.eps EPS] [--optimizer.genertor.weight_decay WEIGHT_DECAY] [--optimizer.genertor.amsgrad AMSGRAD]
                              [--lr_scheduler.discriminator.gamma GAMMA] [--lr_scheduler.discriminator.last_epoch LAST_EPOCH] [--lr_scheduler.discriminator.verbose VERBOSE] [--lr_scheduler.generator.gamma GAMMA] [--lr_scheduler.generator.last_epoch LAST_EPOCH]
                              [--lr_scheduler.generator.verbose VERBOSE]
acoustic-model-trainer: error: Parser key "model.mel_spec": Not of type MelSpectrogram. unsupported operand type(s) for //: 'dict' and 'int'
```

### Things I've tried without success

1. Use an external configuration file for `mel_spectrogram` class as shown [here](https://jsonargparse.readthedocs.io/en/stable/#classes-methods-and-functions)

2. Adding `MelSpectrogram` arguments and then linking those 
```python
        parser.add_class_arguments(MelSpectrogram, "mel_spectrogram", instantiate=True)
      
        parser.link_arguments("mel_spectrogram", "data.mel_spectrogram")
        parser.link_arguments("mel_spectrogram.class_path", "model.mel_spectrogram.class_path")
```
3. Using the following configuration:
```yaml
....
model:
  mel_spec:
    class_path: torchaudio.transforms.MelSpectrogram
    init_args:
      center: false
      hop_length: 256
      mel_fmin: 0.0
      mel_fmax: 8000.0
      mel_fmax_loss: null
      n_fft: 1024
      normalized: false
      num_mels: 80
      sampling_rate: 22050
      win_length: 1024
      # hann_windows: {}
      # mel_bases: {}
....
data:
  mel_spec:
    class_path: torchaudio.transforms.MelSpectrogram
    init_args:
      center: false
      hop_length: 256
      mel_fmin: 0.0
      mel_fmax: 8000.0
      mel_fmax_loss: null
      n_fft: 1024
      normalized: false
      num_mels: 80
      sampling_rate: 22050
      win_length: 1024
      # hann_windows: {}
      # mel_bases: {}
...
```

**Comment by alealv** [comment]
Hi @mauvilsa.
Thanks for the fast reply.
Your example works perfectly as you said I had other mistakes.

Although, specifying another file from where to extract the `init_args` didn't work. Am I missing something else? 

```yaml
data:
  mel_spec: &mel_spec
    class_path: utils.MelSpectrogramDRC
    init_args: mel_spectogram_config.yml
    # init_args:
    #   sample_rate: 22050
    #   n_fft: 1024
    #   win_length: 1024
    #   hop_length: 256
    #   f_min: 0.0
    #   f_max: 8000.0
    #   pad: 384                # (n_fft - hop_length) / 2
    #   n_mels: 80
    #   power: 2
    #   normalized: true
    #   center: false
    #   pad_mode: reflect
    #   onesided: true
    #   njorm: slaney
    #   mel_scale: slaney
model:
  mel_spec:
    <<: *mel_spec
```
